parameters:
  werkint_frontend_mapper.pathsstorage.class:
    Werkint\Bundle\FrontendMapperBundle\Service\PathsStorage

services:
  werkint_frontend_mapper.pathsstorage:
    class: %werkint_frontend_mapper.pathsstorage.class%
