parameters:
  werkint_frontend_mapper.namespace_mapping.class:
    Werkint\Bundle\FrontendMapperBundle\Configuration\NamespaceMapping

services:
  werkint_frontend_mapper.namespace_mapping:
    class: %werkint_frontend_mapper.namespace_mapping.class%
