parameters:
  tommy_js_templating.twig.twigjs.twigjsextension.class:
    Tommy\Bundle\JsTemplatingBundle\Twig\Twigjs\JsTemplatingExtension
  tommy_js_templating.twig.twigjs.twigjstokenparser.class:
    Tommy\Bundle\JsTemplatingBundle\Twig\Twigjs\TwigJsTokenParser
  tommy_js_templating.twig.twigjs.twigjsresulttokenparser.class:
    Tommy\Bundle\JsTemplatingBundle\Twig\Twigjs\TwigJsResultTokenParser

services:
  # Twig - основное расширение сайта
  tommy_js_templating.twig.twigjs.twigjsextension:
    class: %tommy_js_templating.twig.twigjs.twigjsextension.class%
    public: false
    arguments:
      - @twig
      - @tommy_js_templating.twig.twigjs.twigjstokenparser
      - @tommy_js_templating.twig.twigjs.twigjsresulttokenparser
    tags:
      - { name: twig.extension }
  tommy_js_templating.twig.twigjs.twigjstokenparser:
    class: %tommy_js_templating.twig.twigjs.twigjstokenparser.class%
  tommy_js_templating.twig.twigjs.twigjsresulttokenparser:
    class: %tommy_js_templating.twig.twigjs.twigjsresulttokenparser.class%
